ruby:
  config_file: .rubocop.yml
javascript:
  config_file: .jshintrc
  ignore_file: .jshintignore
scss:
  config_file: .scss-lint.yml
eslint:
  config_file: entry_types/paged/packages/pageflow-paged-react/.eslintrc
  ignore_file: .eslintignore
